### ISSUE TITLE
Use install2.R from rocker/r-base

### ISSUE THREAD

**Issue by nuest** [achubaty/rocker-files#1]
Hi! Great effort with these Dockerfiles.

A question from my side: Is there are a particular reason for you not to use the install2.R script as in https://github.com/rocker-org/rocker/blob/master/r-base/Dockerfile#L55 ?

For example https://github.com/achubaty/rocker-files/blob/master/r-spatial-base/Dockerfile#L52

**Comment by achubaty** [comment]
No specific reason other than I'm not very familiar with that script and I had thrown this together the way I knew how. I'll take a look though, thanks.
