### ISSUE TITLE
Use latest gdal version

### ISSUE THREAD

**Issue by nuest** [achubaty/rocker-files#3]
I think one of the great advantages of this Docker image could be that it could help not so tech-savvy people getting the latest packages, such as rgdal, which rely on a gdal version that is not readily available in the Ubuntu sources.

What's your opinion on this? Would you rather stick to the default repos?

**Comment by achubaty** [comment]
Honestly, using the default repos _is_ the simplest (`gdal` is notoriously difficult to deal with ), and I would expect that most people use these defaults.

Also, note that the `gdal` version currently used in these images is recent (July 2016):

``` r
> library(rgdal)
Loading required package: sp
rgdal: version: 1.1-10, (SVN revision 622)
 Geospatial Data Abstraction Library extensions to R successfully loaded
 Loaded GDAL runtime: GDAL 2.1.1, released 2016/07/07
 Path to GDAL shared files: /usr/share/gdal/2.1
 Loaded PROJ.4 runtime: Rel. 4.9.2, 08 September 2015, [PJ_VERSION: 492]
 Path to PROJ.4 shared files: (autodetected)
 Linking to sp version: 1.2-3 
```

**Comment by nuest** [comment]
Right, I did not realize the GDAL version is actually very recent. My apologies, there must have been a recent update, or my memory failed me.

The fact that `gdal` is hard to handle was actually the reason to comment here. A Docker image that builds the most recent version of `gdal`, `PROJ.4` etc. would be perfect to give users access to the most recent versions without going through all of this themselves. Right now this seems not to be an issue.
