### ISSUE TITLE
No more docker repos?!?!

### ISSUE THREAD

**Issue by cjtexas** [achubaty/rocker-files#5]
Why did you remove all your repos from docker hub??? We had some projects with git ci dependencies on them (namely achubaty/r-spatial-base)

**Comment by achubaty** [comment]
Apologies - I didn't realize anyone was (still) using these. I had deprecated these images in favour of versioned rocker images (<https://github.com/rocker-org/rocker-versioned2>) but I will restore these ASAP.

**Comment by achubaty** [comment]
@cjtexas I am building and testing new versions of these that are built from the versioned rocker images, and will start pushing the updated images shortly. Can you please let me know if there are still any breaking changes with these in your CI dependencies?

**Comment by cjtexas** [comment]
Thanks @achubaty, it wasn't a huge deal and we did come up with alternatives in the meantime, but I do appreciate you putting it back up 😄 FYI, I notice the new image size to be quite large at 4.8Gb

**Comment by achubaty** [comment]
Yes, these are larger images because they are using different base images that include an rstudio server instance, to allow interactive development/testing, which is better suited to the workflows I was using these for.

**Comment by cjtexas** [comment]
ok, gotcha. Thanks again for the response 👍
